import = [
  #~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
  #"~/.config/alacritty/catppuccin-macchiato.toml"
  #"~/.config/alacritty/catppuccin-mocha.toml"

  #"~/.config/alacritty/keybindings.toml"
  #~/.config/alacritty/font.toml"
]

shell="/usr/bin/fish"

[window]
opacity=0.6
padding={ x=12, y=12}
decorations="none"

[font]
size = 12.0
normal = { family = "ComicCodeLigatures Nerd Font Mono" }

