theme = "base16_transparent"

[editor]
line-number = "relative"
shell = ["fish", "-c"]
true-color = true
auto-save = true
auto-format = true
idle-timeout = 200

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 10

[editor.lsp]
enable=true
auto-signature-help=true
display-messages = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1
