[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer.config]
check.command = "clippy"
completion.termSearch.enable = true
inlayHints.closureReturnTypeHints.enable = "always"

[[language]]
name = "latex"
language-servers = ["texlab" ]

[language-server.texlab.config.texlab]
#auxDirectory = "tmp"

[language-server.texlab.config.texlab.build]
onSave = true
forwardSearchAfter = true
#args = ["--output-directory=tmp"]

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = ["--synctex-forward", "%l:1:%f", "%p"]

[language-server.texlab.config.texlab.chktex]
onEdit = true
